// Code generated by tailscale.com/cmd/cloner; DO NOT EDIT.

package bgp

import (
	"net/netip"
	"time"
)

// Clone makes a deep copy of Update.
// The result aliases no memory with the original.
func (src *Update) Clone() *Update {
	if src == nil {
		return nil
	}
	dst := new(Update)
	*dst = *src
	dst.Withdrawn = append(src.Withdrawn[:0:0], src.Withdrawn...)
	dst.Attributes = src.Attributes.Clone()
	dst.NLRI = append(src.NLRI[:0:0], src.NLRI...)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _UpdateCloneNeedsRegeneration = Update(struct {
	Withdrawn  []netip.Prefix
	Attributes RawAttributes
	NLRI       []netip.Prefix
}{})

// Clone makes a deep copy of RawAttribute.
// The result aliases no memory with the original.
func (src *RawAttribute) Clone() *RawAttribute {
	if src == nil {
		return nil
	}
	dst := new(RawAttribute)
	*dst = *src
	dst.Data = append(src.Data[:0:0], src.Data...)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _RawAttributeCloneNeedsRegeneration = RawAttribute(struct {
	Flags AttrFlags
	Type  AttrType
	Data  []byte
}{})

// Clone makes a deep copy of Open.
// The result aliases no memory with the original.
func (src *Open) Clone() *Open {
	if src == nil {
		return nil
	}
	dst := new(Open)
	*dst = *src
	if src.Capabilities != nil {
		dst.Capabilities = make([]Capability, len(src.Capabilities))
		for i := range dst.Capabilities {
			dst.Capabilities[i] = *src.Capabilities[i].Clone()
		}
	}
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _OpenCloneNeedsRegeneration = Open(struct {
	ASN          uint32
	HoldTime     time.Duration
	ID           Identifier
	Capabilities []Capability
	fourOctet    bool
}{})

// Clone makes a deep copy of Capability.
// The result aliases no memory with the original.
func (src *Capability) Clone() *Capability {
	if src == nil {
		return nil
	}
	dst := new(Capability)
	*dst = *src
	dst.Data = append(src.Data[:0:0], src.Data...)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _CapabilityCloneNeedsRegeneration = Capability(struct {
	Code CapabilityCode
	Data []byte
}{})

// Clone makes a deep copy of Notification.
// The result aliases no memory with the original.
func (src *Notification) Clone() *Notification {
	if src == nil {
		return nil
	}
	dst := new(Notification)
	*dst = *src
	dst.Data = append(src.Data[:0:0], src.Data...)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _NotificationCloneNeedsRegeneration = Notification(struct {
	Code    NotificationCode
	Subcode uint8
	Data    []byte
}{})

// Clone makes a deep copy of RouteRefresh.
// The result aliases no memory with the original.
func (src *RouteRefresh) Clone() *RouteRefresh {
	if src == nil {
		return nil
	}
	dst := new(RouteRefresh)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _RouteRefreshCloneNeedsRegeneration = RouteRefresh(struct {
	Family Family
}{})
