package bgp

// Clone methods are generated by tailscale.com/cmd/cloner, wired as a go.mod
// tool dependency. The generated _CloneNeedsRegeneration guards break the
// build when a cloned type gains a field, until this is re-run.
//go:generate go tool cloner -copyright=false -type Update,RawAttribute,Open,Capability,Notification,RouteRefresh,GracefulRestartConfig
